# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Don't build NaCl docs during Netlify preview builds.
  # These take forever and we don't need them for PR previews.
  ELEVENTY_IGNORE_NCAL=true

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
