# This is the same as cloudbuild.yaml, but specifically for handling PR requests. Deploys to staging.
steps:
- name: node
  entrypoint: npm
  args: ['ci']
- name: node
  entrypoint: npm
  args: ['run', 'production']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--project=chrome-apps-doc-staging-2020', '--version=gh-$_PR_NUMBER']
- name: 'bash'
  args:
  - '-c'
  - |
    echo "Uploaded to https://gh-$_PR_NUMBER-dot-chrome-apps-doc-staging-2020.appspot.com"
    # TODO: write this back to GitHub somehow
