# This is a test Cloud Build step to test variable substitution.
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo gcloud app deploy ${_EXTRA_GCLOUD_ARGS:-} --after